### PR TITLE
replace "alexandria-v2" with "alexandria"

### PR DESCRIPTION
**Pull request by dunn**
Should only be merged when the repository itself can be renamed.

### CODE REVIEW

**Comment by jcoyne** [comment]
Can you rebase this. It won't merge cleanly now.

**Comment by dunn** [comment]
Rebased!

**Comment by dunn** [comment]
Oops, fresh conflicts. Just let me know when you're planning to merge this and I'll rebase it then.

**Comment by mark-dce** [comment]
Superseded by #673

**Pull request closed without merging**
